/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 20-jun.-2025 10:36:32 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */
use erp
go

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_asignacion_tuno_empleados]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [asignacion_tuno] DROP CONSTRAINT [FK_asignacion_tuno_empleados]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_asignacion_tuno_turno]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [asignacion_tuno] DROP CONSTRAINT [FK_asignacion_tuno_turno]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_registro_marcacion_empleados]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [registros_marcacion] DROP CONSTRAINT [FK_registro_marcacion_empleados]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_vacaciones_empleados]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [vacaciones_feriados] DROP CONSTRAINT [FK_vacaciones_empleados]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[asignacion_tuno]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [asignacion_tuno]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[empleados]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [empleados]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[registros_marcacion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [registros_marcacion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[turno]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [turno]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[vacaciones_feriados]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [vacaciones_feriados]
GO

/* Create Tables */

CREATE TABLE [asignacion_tuno]
(
	[codigo] int NOT NULL,
	[empleado] int NULL,
	[fecha_asignacion] date NULL,
	[turno] int NULL
)
GO

CREATE TABLE [empleados]
(
	[codigo] int NOT NULL,
	[nombre] varchar(50) NULL,
	[fecha] datetime NULL,
	[cargo] int NULL,
	[unidad_de_negocio] int NULL,
	[estado] int NULL
)
GO

CREATE TABLE [registros_marcacion]
(
	[codigo] int NOT NULL,
	[empleado] int NULL,
	[fecha] date NULL,
	[hora_entrada_marcada] time(7) NULL,
	[hora_salida_marcada] time(7) NULL
)
GO

CREATE TABLE [turno]
(
	[codigo] int NOT NULL,
	[nombre] varchar(50) NULL,
	[hora_inicio] time(7) NULL,
	[hora_final] time(7) NULL,
	[minutos_tolerancia] int NULL
)
GO

CREATE TABLE [vacaciones_feriados]
(
	[codigo] int NOT NULL,
	[empleado] int NULL,
	[tipo_evento] varchar(50) NULL,
	[fecha_inicio] datetime NULL,
	[fecha_fin] datetime NULL,
	[aprobado] bit NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [asignacion_tuno] 
 ADD CONSTRAINT [PK_asignacion_tuno]
	PRIMARY KEY CLUSTERED ([codigo] ASC)
GO

ALTER TABLE [empleados] 
 ADD CONSTRAINT [PK_empleados]
	PRIMARY KEY CLUSTERED ([codigo] ASC)
GO

ALTER TABLE [registros_marcacion] 
 ADD CONSTRAINT [PK_registro_marcacion]
	PRIMARY KEY CLUSTERED ([codigo] ASC)
GO

ALTER TABLE [turno] 
 ADD CONSTRAINT [PK_turno]
	PRIMARY KEY CLUSTERED ([codigo] ASC)
GO

ALTER TABLE [vacaciones_feriados] 
 ADD CONSTRAINT [PK_vacaciones]
	PRIMARY KEY CLUSTERED ([codigo] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [asignacion_tuno] ADD CONSTRAINT [FK_asignacion_tuno_empleados]
	FOREIGN KEY ([empleado]) REFERENCES [empleados] ([codigo]) ON DELETE Cascade ON UPDATE Cascade
GO

ALTER TABLE [asignacion_tuno] ADD CONSTRAINT [FK_asignacion_tuno_turno]
	FOREIGN KEY ([turno]) REFERENCES [turno] ([codigo]) ON DELETE Cascade ON UPDATE Cascade
GO

ALTER TABLE [registros_marcacion] ADD CONSTRAINT [FK_registro_marcacion_empleados]
	FOREIGN KEY ([empleado]) REFERENCES [empleados] ([codigo]) ON DELETE Cascade ON UPDATE Cascade
GO

ALTER TABLE [vacaciones_feriados] ADD CONSTRAINT [FK_vacaciones_empleados]
	FOREIGN KEY ([empleado]) REFERENCES [empleados] ([codigo]) ON DELETE Cascade ON UPDATE Cascade
GO
